### ISSUE TITLE
How to get every line which is being printed to the Terminal?

### ISSUE THREAD

**Issue by gebes** [Minecrell/TerminalConsoleAppender#10]
(This is a qeustion/suggestion, but I dont know how to mark as question)

If there is a message being printed to the Terminal, is there a way to get that line as String?
E.g.: logger.info("my message") and is there then any way, to get "my message" with the format (time and date) before the message itself?
So when something gets logged, I want to get it somewhere in Java as String

I appreciate any help

**Comment by stephan-gh** [comment]
It depends on what you would like to do:

- If you'd like to get all log messages to print them somewhere else (e.g. to a file, ...), then you would use a [Log4j Appender](https://logging.apache.org/log4j/2.x/manual/appenders.html).
- If you'd like to filter certain messages (i.e. prevent them from being printed), then you would use a [Log4j Filter](https://logging.apache.org/log4j/2.x/manual/filters.html).
- If you'd like to change the way messages are printed (i.e. the date/time format, colors, ...), then you would use a [Log4j Layout](https://logging.apache.org/log4j/2.x/manual/layouts.html).
- If you'd like to transform messages before they are printed, then you would use a [Log4j Converter](https://logging.apache.org/log4j/2.x/manual/plugins.html#Converters).

As you can see, TerminalConsoleAppender does not provide a way to get all messages printed to the terminal. However, Log4j has several places where you can intercept/transform messages that are logged, but it depends on what exactly you would like to do.
