### ISSUE TITLE
ERROR StatusLogger Unrecognized format specifier

### ISSUE THREAD

**Issue by pedxyuyuko** [Minecrell/TerminalConsoleAppender#15]
Hellow Minecrell,
When I using this Appender, the program shows those error message and the log4j2 doesn't work anymore.
![image](https://user-images.githubusercontent.com/39913604/78418429-8d75a900-766e-11ea-87cd-bb0cb8d0b614.png)

This is my log4j2.xml
![image](https://user-images.githubusercontent.com/39913604/78418432-98303e00-766e-11ea-8a7d-a99f08c738b8.png)

**Comment by stephan-gh** [comment]
This looks a bit like you are using a shaded JAR (i.e. one that bundles all dependencies), but you don't merge the `Log4J2Plugins.dat` file properly. You need a Maven/Gradle plugin to merge the one from `log4j2-core` with the one in `TerminalConsoleAppender`.

See e.g. https://bugs.mojang.com/browse/MC-118594 for an explanation.

**Comment by pedxyuyuko** [comment]
Thanks for your 

> This looks a bit like you are using a shaded JAR (i.e. one that bundles all dependencies), but you don't merge the `Log4J2Plugins.dat` file properly. You need a Maven/Gradle plugin to merge the one from `log4j2-core` with the one in `TerminalConsoleAppender`.
> 
> See e.g. https://bugs.mojang.com/browse/MC-118594 for an explanation.

Thanks for your response!
So I should use a Maven/Gradle plugin to put the ``Log4J2Plugins.dat`` and the .dat file in ``TerminalConsoleAppender`` to one file?

**Comment by stephan-gh** [comment]
yes

**Comment by pedxyuyuko** [comment]
Thanks! It didn't print error anymore. But there is another problem that the sign ``>`` doesn't keep in the bottom of the terminal like this 
![image](https://user-images.githubusercontent.com/39913604/78450904-b02ab080-76b4-11ea-8a7a-1e8a3dc88bf9.png)

here is my configs:
![image](https://user-images.githubusercontent.com/39913604/78450914-bcaf0900-76b4-11ea-9c35-ec5741b4e38c.png)
![image](https://user-images.githubusercontent.com/39913604/78450924-c89acb00-76b4-11ea-9ef2-0dffef6ba8d2.png)
![image](https://user-images.githubusercontent.com/39913604/78451011-537bc580-76b5-11ea-9228-290ddf22cbaf.png)

**Comment by SaigyoujiYuyuko233** [comment]
I try to add the ``com.github.edwgiz.maven_shade_plugin.log4j2_cache_transformer`` transformer in the  pom.xml but when I try to package it, it shows: 
![image](https://user-images.githubusercontent.com/39913604/78451382-e289dd00-76b7-11ea-9006-cd327b62252f.png)
![image](https://user-images.githubusercontent.com/39913604/78451383-e61d6400-76b7-11ea-8db4-925e96c67fa1.png)

**Comment by pedxyuyuko** [comment]
When I complex it successfully, I look up the ``Log4j2Plugins.dat`` and found 
![image](https://user-images.githubusercontent.com/39913604/78452070-bf612c80-76bb-11ea-881c-899cf169ccdf.png)

But the program didn't work properly.
![image](https://user-images.githubusercontent.com/39913604/78452129-0ea75d00-76bc-11ea-9cb7-a51ee034e51b.png)
![4SP}H_P66MOO3 XNX$60`RI](https://user-images.githubusercontent.com/39913604/78452131-11a24d80-76bc-11ea-89be-a186b45b50ac.png)

Accept Behave:
```
21:30:29.631 [Thread-3] INFO  ServerChat | chat.type.announcement
21:30:31.528 [Thread-3] INFO  ServerChat | <4sddff> aa
Chat >> test
21:30:37.031 [Thread-3] INFO  ServerChat | chat.type.announcement
21:30:40.094 [Thread-3] INFO  ServerChat | <4sddff> test
Chat >>
```

**Comment by stephan-gh** [comment]
Have you added a dependency on either Jansi or JNA? (see README)

**Comment by pedxyuyuko** [comment]
> Have you added a dependency on either Jansi or JNA? (see README)
Like this?..
![image](https://user-images.githubusercontent.com/39913604/78452358-73af8280-76bd-11ea-8cd4-4a1e9bb652d3.png)
![image](https://user-images.githubusercontent.com/39913604/78452367-7d38ea80-76bd-11ea-8f52-213171bd0aab.png)

**Comment by stephan-gh** [comment]
You are setting a lot of weird options there. I would suggest that you use `SimpleTerminalConsole` (see README), since it handles constructing the `Terminal` and `LineReader` for you.

**Comment by pedxyuyuko** [comment]
> You are setting a lot of weird options there. I would suggest that you use `SimpleTerminalConsole` (see README), since it handles constructing the `Terminal` and `LineReader` for you.

Thanks! I will try now

**Comment by pedxyuyuko** [comment]
> You are setting a lot of weird options there. I would suggest that you use `SimpleTerminalConsole` (see README), since it handles constructing the `Terminal` and `LineReader` for you.

Ohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh!!!!! Thanks you very very very very much!!!! I am suffering for the terminal like this for AMOST ONE YEAR!!!!! I am so exciting that I amost cry out!!!! YOU ARE AWESOME!!! THIS PROJECT IS AWESOME!!!!!!

**Comment by pedxyuyuko** [comment]
For extra:
I pull up your awesome SimpleTerminalConsole out for customize prompt. This is my code:
```
public static Terminal terminal;
public static LineReader lineReader;
........
terminal = TerminalConsoleAppender.getTerminal();

if (terminal != null) {
	lineReader = LineReaderBuilder.builder().terminal(terminal).build();
} else {
	lineReader = LineReaderBuilder.builder().terminal((Terminal) System.in).build();
}

lineReader.setOpt(LineReader.Option.DISABLE_EVENT_EXPANSION);
lineReader.unsetOpt(LineReader.Option.INSERT_TAB);
TerminalConsoleAppender.setReader(lineReader);

while (true) {
	lines = lineReader.readLine("Chat > ");
	System.out.printnl(lines);
}
```

**Comment by stephan-gh** [comment]
I suppose I should make that configurable... But yeah, your code above looks much better :)

**Comment by pedxyuyuko** [comment]
:)  Thanks for this awesome project again
