### ISSUE TITLE
Help wanted testing upgrade to JLine 3.20.0

### ISSUE THREAD

**Issue by stephan-gh** [Minecrell/TerminalConsoleAppender#19]
In https://github.com/Minecrell/TerminalConsoleAppender/commit/ddb7dc1ae6abf6d5d07488c6e6087667070cda9d I updated TCA to use JLine 3.20.0 (from JLine 3.12.1 so far). It tested it briefly with ServerListPlusServer (which uses TCA now too \o/) on Linux and it seems to work just fine.

But in the past JLine/Jansi/... upgrades have often caused some weird regressions, particularly on Windows so it would be good to have some more testing. I don't really use Windows/macOS/whatever anymore so I could use some help to make sure that it works well on other platforms as well. :)

I'm hoping some people from the projects using TCA can help test this to make sure it works well before I tag a new release. The upgrade is in the latest TCA `1.3.0-SNAPSHOT` that you can get from `https://oss.sonatype.org/content/repositories/snapshots/`. Don't forget to update `org.jline:jline-terminal-jansi` (or JNA) to 3.12.0 as well.

FWIW, pinging some people who might be interested to avoid regressions in TCA :) @electronicboy @zml2008 @astei

**Comment by zml2008** [comment]
I'll bump Sponge up to the 1.3.0 snapshot and let it sit for a while, though all appears fine from local testing on Windows.

fwiw, Sponge has been on JLine 3.19.0 on our 1.16 branch for a while now and we haven't had issues.

**Comment by stephan-gh** [comment]
OK, since nobody reported any problems I think I'm gonna go ahead and push 1.3.0 to Maven central. To be honest, I forgot how to do all the signing etc but will probably figure it out again :D
