### ISSUE TITLE
Colors not working

### ISSUE THREAD

**Issue by BlueTree242** [Minecrell/TerminalConsoleAppender#24]
Hi, i am trying to use that library on my standalone project. However Minecraft Formatting (i know it is deprecated, but i want to use it) is not working as expected

1. Not working in intellij, while log4j's highlight colors are working perfectly, and it works if i use the override property
2. I am getting a weird character in the place of the color code, even if colors aren't even applied:
![image](https://user-images.githubusercontent.com/69328929/187075921-017304ef-aae2-40dc-a3a4-59135b2b29ed.png)

Am i doing something incorrectly?

**Comment by stephan-gh** [comment]
> Am i doing something incorrectly?

I don't know, you didn't post any of your configuration or code so I could just make bad guesses. :/

**Comment by BlueTree242** [comment]
https://github.com/BlueTree242/PreBot/blob/f8f23fd9e2aa9277abbee87b788c2b85fa16ae35/launcher/src/main/resources/log4j2.xml this is my log4j2.xml

**Comment by stephan-gh** [comment]
So does it only not work in IntelliJ?

**Comment by BlueTree242** [comment]
it works in windows terminal, and in intellij if i use override property, and im getting that weird character in both cases

**Comment by stephan-gh** [comment]
For the IntelliJ detection: It's complicated to get it right, I think the detection might not work correctly at the moment if you run using the Gradle task in IntelliJ. (It should work when using the normal IntelliJ run configurations.)

That char looks like you put more than `§c` in the string. I'd say the color (`§c`?) is applied correctly but there is some garbage before it.

**Comment by BlueTree242** [comment]
yup, i wanna remove the garbage

**Comment by BlueTree242** [comment]
> For the IntelliJ detection: It's complicated to get it right, I think the detection might not work correctly at the moment if you run using the Gradle task in IntelliJ. (It should work when using the normal IntelliJ run configurations.)
> 
> That char looks like you put more than `§c` in the string. I'd say the color (`§c`?) is applied correctly but there is some garbage before it.

Well i only put a color code, even if i did multiple... It shouldn't act like that right?

**Comment by stephan-gh** [comment]
If you'd do e.g. `§§c` it would likely produce something like this, since the converter only touches valid color codes.

**Comment by stephan-gh** [comment]
(Although maybe one would expect the terminal to display `§` and not this garbage...)

**Comment by BlueTree242** [comment]
im sure i didn't do that, ive wrote the color code 5 separate times i never saw extra §

**Comment by stephan-gh** [comment]
Uh, the garbage is always only at the beginning of the line?

**Comment by BlueTree242** [comment]
no, i tried putting the color code in middle and the garbage was in middle too

**Comment by stephan-gh** [comment]
I'd suggest removing the `{strip}` from the `%minecraftFormatting` in the `RollingRandomAccessFile` output, and then look at the log file with a proper editor to find out what kind of char this really is (the "?" doesn't tell much).

**Comment by BlueTree242** [comment]
good idea, ill try

**Comment by BlueTree242** [comment]
![image](https://user-images.githubusercontent.com/69328929/187094887-3fff650a-2f93-44f6-92b6-e158c11ea477.png)
i see this when i open logs in intellij

**Comment by stephan-gh** [comment]
Open it in a different editor? Perhaps even in a hex editor if necessary.

**Comment by BlueTree242** [comment]
i tried visual studio code, and i got the same thing, i tried notepad and i got this: 
![image](https://user-images.githubusercontent.com/69328929/187275304-5b5b5e13-b938-4411-ad2b-13ddfacde40a.png)
i don't have any more editors, do you suggest any others

**Comment by stephan-gh** [comment]
Looks like there is a Hex Editor extension for vscode that would allow you to see the numeric value of that char: https://marketplace.visualstudio.com/items?itemName=ms-vscode.hexeditor (no idea how to use it)

**Comment by BlueTree242** [comment]
ok. using hex editor, i got 3 dots in location of garbage, this is when clicking each in order:
![image](https://user-images.githubusercontent.com/69328929/187388988-c9d0aaed-799f-4b6a-a888-f08285f8f8fd.png)
![image](https://user-images.githubusercontent.com/69328929/187389034-4ed993a6-8a35-40b3-b473-0d6e339e757d.png)
![image](https://user-images.githubusercontent.com/69328929/187389075-7eb92839-d2e1-4d91-a727-70ede2bcb4a2.png)

**Comment by stephan-gh** [comment]
OK very strange, not sure where that'd come from. If you want you can upload your current code and I can take a brief look if I see something. (Can't seem to find the colored message in the repo you linked.)

**Comment by BlueTree242** [comment]
i cannot use color codes in the repo if it's not working, if you want to reproduce locally, clone the repo, add a color code [here](https://github.com/BlueTree242/PreBot/blob/develop/core/src/main/java/me/bluetree242/prebot/core/PreBotMain.java#L92), and run the main class [here](https://github.com/BlueTree242/PreBot/blob/develop/launcher/src/main/java/me/bluetree242/prebot/Main.java), if you want to try windows terminal build it and run the prebot jar in `launcher/build/libs`

**Comment by BlueTree242** [comment]
if required i can make a test branch for you

**Comment by BlueTree242** [comment]
i noticed a very important thing, i noticed that the compiled string contained the garbage, which means that this library might be innocent not causing any trouble

**Comment by BlueTree242** [comment]
Yup, that was the problem. for anyone having this problem set your encoding in gradle to utf8 in all project (if multi module). Thanks for helping
