### ISSUE TITLE
Timeline for next published release

### ISSUE THREAD

**Issue by zachbr** [Minecrell/TerminalConsoleAppender#7]
An issue was fixed in a newer version of JLine than is included in the 1.1.1 TCA release.
It looks like master includes a version of JLine with the relevant bug fix. Is there any timeline or known blockers for the next release?

I'd be happy to help you test if that's a concern. Thanks, and thanks for TCA 👍

**Comment by stephan-gh** [comment]
I was hoping for https://github.com/jline/jline3/pull/401
At the moment, it makes using Log4j's own `%highlight` really ugly (empty line after each message). Only TCA's own `%highlightError{}` has a workaround for this.

**Comment by stephan-gh** [comment]
In general, you can update JLine independently from TCA. Just override these two dependencies: https://github.com/Minecrell/TerminalConsoleAppender/blob/46e9b1fe67561a672f8efaf735c5f04852d5256b/build.gradle.kts#L24-L25

It should usually work just fine with newer JLine versions. The JLine version used by TCA only represents the recommended version it was tested with.

**Comment by zachbr** [comment]
Thanks for the prompt responses, I'll take a look at that soon 👍

**Comment by stephan-gh** [comment]
My PR was just merged and JLine 1.12.0 was released. I have updated TCA to use the new release.
For now, using the new JLine release is blocked by https://github.com/jline/jline3/issues/411, however.
