### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by gebes** [Minecrell/TerminalConsoleAppender#8]
Hey Minecrell, I don't get this appender working.

Because of this, I want to ask, if you can give me any working example project.

**So this isn't a true issue, because I don't get it to work, so its my fault. Srry for that**

Have a great day^^

**Comment by stephan-gh** [comment]
Well, it is used in many projects:
  - https://github.com/PaperMC/Paper
  - https://github.com/PaperMC/Waterfall
  - https://github.com/SpongePowered/SpongeVanilla
  - https://github.com/MinecraftForge/MinecraftForge
  - https://github.com/VelocityPowered/Velocity
  - ...

Not sure if any of those are particularly simple examples, though. https://github.com/VelocityPowered/Velocity might be the easiest to look at.

However, it might be easier if you share what you have and I check if I see something wrong.

**Comment by gebes** [comment]
Here is the [repository](https://github.com/GebesPlays/ConsoleTest2/tree/master) to my test Project
I never used jLine before, and the only experience I ever made at making Terminals/Consoles was with Google's Lanterna API. So I only want to make a Console like a Vanilla Minecraft Server, Bukkit, Spigot... I tried by looking at Spigots Sourcecode, but, it's just a mess and I couldn't figure out

So I appreciate any help or any simpler explanation because I am not experienced with jLine at all

**Comment by stephan-gh** [comment]
- It will stop listening for commands if you return `false` in `isRunning`, so you should rather hard-code this to `true`:
https://github.com/GebesPlays/ConsoleTest2/blob/a9620fac1c42a0d030c2517833c5b13dcfb1adf1/src/main/java/eu/gebes/ExampleConsole.java#L9

- You need to choose one of the patterns here: https://github.com/GebesPlays/ConsoleTest2/blob/a9620fac1c42a0d030c2517833c5b13dcfb1adf1/src/main/resources/log4j2.xml#L5-L9
  They all do something slightly different, check the README and [Log4j 2 configuration manual](https://logging.apache.org/log4j/2.x/manual/configuration.html)

- Please avoid making a `Log` class. It's more or less a "bad copy" of the `Logger` class and you can just use the `Logger` directly. (e.g. `LogManager.getLogger().info("Hello World!");`)

**Comment by mikroskeem** [comment]
Or just set up logger field (like `private static final Logger logger = LogManager.getLogger(CurrentClass.class);`) and use that

**Comment by gebes** [comment]
Thanks for the help! Now it is working perfectly^^
