### ISSUE TITLE
Cant export with maven

### ISSUE THREAD

**Issue by gebes** [Minecrell/TerminalConsoleAppender#9]
Hello,

I want to export the project with maven, but I always get the error, that it can't find the SimpleTerminalConsole class.

[Here some helpful images](https://imgur.com/a/eyjfNaw) of the artifacts and dependencies
and [here the pom.xml](https://pastebin.com/LLncP8cP)

So I have no clue, what I've done wrong, I just want to export the file with maven

I appreciate every help

**Comment by stephan-gh** [comment]
If you build your project using Maven, you should avoid using the packaging tools for IntelliJ IDEA projects (aka "Artifacts"). Instead, set up maven-shade-plugin to produce a shaded JAR and build using Maven:

https://maven.apache.org/plugins-archives/maven-shade-plugin-2.1/

**Comment by gebes** [comment]
Okay, thanks for that. Now I can export, but how do I print to the console?
In the SimpleTerminalConsole child, I can print anything with System.out without errors, but if I use the logger, [I get following error in terminal](https://imgur.com/a/t0I7eN2)

Then I tried to print with System.out or the Logger to the console, but I get nothing, no error, no message, etc.
I tried it in the main method to print something

[Here the Git repository](https://github.com/GebesPlays/TerminalConsoleAppender)

**Comment by stephan-gh** [comment]
You need to configure https://github.com/edwgiz/maven-shaded-log4j-transformer

**Comment by gebes** [comment]
Can you help me, configuring the current pom.xml? I tried [this](https://pastebin.com/0qng5ABL), but I still get the same error

**Comment by stephan-gh** [comment]
Did you actually re-build the project using Maven (e.g. `mvn clean package`)? It seems to work just fine. Also make sure you run `target/WashbowlBot-1.0.jar`.

**Comment by stephan-gh** [comment]
Ah wait, I see what you mean. You need to add the transformer to the configuration as described in the README:

https://gist.github.com/Minecrell/dc1edfb7f0206eb3d6dabbfa7d6e153c/revisions

Then it works somewhat ;)

**Comment by gebes** [comment]
So, I edited the pom.xml, then I went to Maven/Lifecycle -> once "clean" and then "package" like on [this picture](https://imgur.com/a/wlvHNfr)

Then I run the jar "target/WashbowlBot-1.0.jar" from a .bat file and same result with log4j2

**Comment by gebes** [comment]
Oh excuse me! I got it working, but when entering the first command I got this message

2019-08-22 15:52:15,366 main ERROR appender TerminalConsole has no parameter that matches element PatternLayout
2019-08-22 15:52:15,413 main WARN Advanced terminal features are not available in this environment
[15:52:15 INFO]: §4Command > help

After entering the first command it works, and how do I send colors?

**Comment by gebes** [comment]
And I can only Log to the console, when the "runCommand#String" method is called, only there. If I try to log somewhere else, It does not work

**Comment by gebes** [comment]
Okay, fixed most of the problems

Thank you for the help! I search for 2 years for a Minecraft/Bukkit/etc... like Terminal. Thank you!
